version: '3'
services:
  osmquery:
    build:
      context: ./apis/osmquery
      dockerfile: Dockerfile
    ports:
      - "3000:5000"
    env_file:
      - ./.env

  nlp:
    build:
      context: ./apis/nlp
      dockerfile: Dockerfile
    ports:
      - "4000:8080"
    volumes:
      - ./volumes/nlp/model:/app/model
    env_file:
      - ./.env

  osmtagsearch:
    build:
      context: ./apis/osmtagsearch
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    env_file:
      - ./.env
    volumes:
      - ./volumes/osmtagsearch/model:/app/model

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xmx1024m
    ports:
      - "9200:9200"
    env_file:
      - ./.env
    networks:
      - elastic
    volumes:
      - ./volumes/osmtagsearch/es_data:/usr/share/elasticsearch/data
    user: 1000:1000
  
networks:
  elastic: